on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
     - name: docker login
       run: |
         echo ${{ inputs.docker_hub_token }} > password.txt
         cat password.txt | docker login --username ${{ inputs.docker_hub_user }} --password-stdin
       shell: bash
     - name: docker build 
       run: docker build -t fastapisqlalchemy .
       shell: bash